*-----------------------------------------------------------
* Title      : constants
* Written by : Henry Wrightson
* Date       : 16/8/2026
* Type       : Include file
* Depends on : 
* Description: Constants that the main program depends on
*-----------------------------------------------------------

; graphics constants
RES_X               equ     650
RES_Y               equ     650

; colour constants all formatted $00BBGGRR
COLOUR_BACKGROUND   equ     $00000000   ; black

COLOUR_WHITE        equ     $00ffffff   ; white
COLOUR_RED          equ     $000000ff   ; red
COLOUR_GREEN        equ     $000d9c33   ; green

; polygon constants
MAX_VERTICES        equ     20
*~Font name~Courier New~
*~Font size~10~
*~Tab type~1~
*~Tab size~4~
